package votingsystem;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ankit
 */

public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    static String pm,p,vs,s,vp,name3,eid;
   
    public UserInterface() {
        initComponents();
        
    }
    
    public UserInterface(String s,String b) {
        initComponents();
        name3=s;
        eid=b;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PM = new javax.swing.JComboBox<>();
        P = new javax.swing.JComboBox<>();
        VP = new javax.swing.JComboBox<>();
        S = new javax.swing.JComboBox<>();
        VS = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Confirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMMouseClicked(evt);
            }
        });

        jLabel1.setText("VoTe For The Best");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jLabel2.setText("Prime Minister:");

        jLabel3.setText("President:");

        jLabel4.setText("Vice President:");

        jLabel5.setText("Secretary:");

        jLabel6.setText("Vice Secretary:");

        Confirm.setText("Confirm");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PM, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VP, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VS, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addComponent(VS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(Confirm))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PMMouseClicked

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        // TODO add your handling code here:
        PM.setEnabled(false);
        P.setEnabled(false);
        VP.setEnabled(false);
        S.setEnabled(false);
        VS.setEnabled(false);
        Submit.setEnabled(true);
        Confirm.setEnabled(false);
    }//GEN-LAST:event_ConfirmActionPerformed
    public static String pm1,p1,vp1,s1,vs1;
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        pm1=PM.getSelectedItem().toString();
        p1=P.getSelectedItem().toString();
        vp1=VP.getSelectedItem().toString();
        s1=S.getSelectedItem().toString();
        vs1=VS.getSelectedItem().toString();
        System.out.print(name3);
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/VotingSystem","root","root");
                String sql="insert into SaveResult values(?,?,?,?)";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.setString(1, name3);
                ps.setString(2, pm1);
                ps.setString(3, "PM");
                ps.setString(4, eid);
                String sql1="insert into SaveResult values(?,?,?,?)";
                PreparedStatement ps1=con.prepareStatement(sql1);
                ps1.setString(1, name3);
                ps1.setString(2, p1);
                ps1.setString(3, "P");
                ps1.setString(4, eid);
                String sql2="insert into SaveResult values(?,?,?,?)";
                PreparedStatement ps2=con.prepareStatement(sql2);
                ps2.setString(1, name3);
                ps2.setString(2, vp1);
                ps2.setString(3, "VP");
                ps2.setString(4, eid);
                String sql3="insert into SaveResult values(?,?,?,?)";
                PreparedStatement ps3=con.prepareStatement(sql3);
                ps3.setString(1, name3);
                ps3.setString(2, s1);
                ps3.setString(3, "S");
                ps3.setString(4, eid);
                String sql4="insert into SaveResult values(?,?,?,?)";
                PreparedStatement ps4=con.prepareStatement(sql4);
                ps4.setString(1, name3);
                ps4.setString(2, vs1);
                ps4.setString(3, "VS");
                ps4.setString(4, eid);
                
                int i=ps.executeUpdate();
                int j=ps1.executeUpdate();
                int k=ps2.executeUpdate();
                int l=ps3.executeUpdate();
                int m=ps4.executeUpdate();
                
                System.out.println("Hello");
                if((i>0)&&(j>0)&&(k>0)&&(l>0)&&(m>0))
                {
                   JOptionPane.showMessageDialog(null,"values Saved");
                    this.setVisible(false);
                    VotingLogin v1= new VotingLogin();
                    v1.setVisible(true);
                }
        }
        catch(Exception e)
        {
        
        }
        
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public void PMPerformed(String a)
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/VotingSystem","root","root");
            String sql="select name from Candidates where post='Prime Minister' and E_Id=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1, a);
            ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                    pm=rs.getString("name");
                    System.out.println(pm);
                    PM.addItem(pm);
                }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    public void subhide()
    {
        Submit.setEnabled(false);
    }
    
    public void PPerformed(String b)
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/VotingSystem","root","root");
            String sql="select name from Candidates where post=? and E_Id=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,"President");
            ps.setString(2,b);
            ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                    p=rs.getString("name");
                    System.out.println(p);
                    P.addItem(p);
                }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    public void VPPerformed(String c)
    {
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/VotingSystem","root","root");
            String sql="select name from Candidates where post='Vice President' and E_Id=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,c);
            ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                    vp=rs.getString("name");
                    System.out.println(vp);
                    VP.addItem(vp);
                }
        }
        catch(Exception e)
        {
            
        }
    }
    
    public void SPerformed(String d)
    {
        String p="Secretary";
        System.out.println(d);
        try{ 
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/VotingSystem","root","root");
            String sql="select name from Candidates where post=? and E_Id=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,p);
            ps.setString(2,d);
            ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                    s=rs.getString("name");
                    System.out.println(s);
                    S.addItem(s);
                }
        }
        catch(Exception e)
        {
            
        }
    }
    
    public void VSPerformed(String q)
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/VotingSystem","root","root");
            String sql="select name from Candidates where post='Vice Secretary' and E_Id=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,q);
            ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                    vs=rs.getString("name");
                    System.out.println(vs);
                    VS.addItem(vs);
                }
        }
        catch(Exception e)
        {
            
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm;
    private javax.swing.JComboBox<String> P;
    private javax.swing.JComboBox<String> PM;
    private javax.swing.JComboBox<String> S;
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> VP;
    private javax.swing.JComboBox<String> VS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
